image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test:
  script:
    - python -m pytest
  tags:
    - dsi

deploy:
  image: docker:dind
  script:
    - docker system prune
    - docker build . -t flasknlp:latest
  tags:
    - dsi
  only:
    - master